#! /bin/sh
# opttest - test getopt handling of options

parm=`getopt "ab:" "$@"`
res=$?
echo $parm, $res

[[ $res != 0 ]] && {
    echo "Usage: `basename $0` [-a] [-b name] [files]" 1>&2
    exit 1
}

# "set --" : 重新设置命令行参数
set -- $parm

echo "Before loop, command line has: $*"
aflag=0  name=NONE
while :
do
    case "$1" in
    -a) aflag=1 ;;
    -b) shift; name="$1" ;;
    --) break ;;
    esac
    shift
done
shift    # Remove the trailing --

echo "aflag=$aflag , name=$name , Files are $*"
